"""Deploy a trained rsl_rl PPO actor onto the MuJoCo MJCF of the mos2026_2 robot.

The MJCF must already be generated by `tools/usd_to_mjcf.py`. The script:
  - Loads the .pt checkpoint, picks out the actor_state_dict, and rebuilds the
    [256, 256, 128]-ELU MLP from the rsl_rl RslRlPpoActorCriticCfg.
  - Reproduces Isaac Lab's 45-dim observation: root_lin_vel_b, root_ang_vel_b,
    projected_gravity_b, joint_pos_rel, joint_vel, prev_actions.
  - Reproduces Isaac Lab's action pipeline: clip action_clip=1.5,
    processed = action_scale * action + default_pos, fed to MuJoCo position
    actuators (kp=25, kv=0.5).
  - Runs at 50 Hz control over a 200 Hz MuJoCo sim (decimation=4), matching
    the env config.
  - --viewer launches the interactive mujoco viewer; --headless runs N steps
    silently for validation.

Example:
    python deploy/mujoco/play_mujoco.py \
        --checkpoint logs/rsl_rl/mos2026_2_closed_usd/2026-05-14_11-23-51/model_600.pt

    python deploy/mujoco/play_mujoco.py --headless --duration 5 \
        --checkpoint logs/rsl_rl/mos2026_2_closed_usd/2026-05-14_11-23-51/model_600.pt
"""
from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import numpy as np
import torch
from torch import nn

import mujoco
import mujoco.viewer

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MJCF = REPO_ROOT / "deploy/mujoco/assets/mos2026_2.xml"

# Mirror of the Isaac Lab env config — kept here so the deploy script is
# self-contained (importing the env config drags Isaac Lab's full stack).
ACTUATED_JOINTS = [
    "fl_hip", "fr_hip", "rl_hip", "rr_hip",
    "fl_thigh", "fr_thigh", "rl_thigh", "rr_thigh",
    "fl_shank_link", "fr_shank_link_a", "rl_shank_link_a", "rr_shank_link_a",
]
DEFAULT_JOINT_POS = np.array([
    0.06, 0.06, -0.06, -0.06,  # hips
    0.0, 0.0, 0.0, 0.0,        # thighs
    0.0, 0.0, 0.0, 0.0,        # shank links
])
ACTION_SCALE = 0.5
ACTION_CLIP = 1.5
INIT_HEIGHT = 0.35
INIT_QUAT_WXYZ = np.array([1.0, 0.0, 0.0, 0.0])
COMMANDED_LIN_VEL_XY = np.array([1.0, 0.0])
COMMANDED_ANG_VEL_Z = 0.0
CONTROL_HZ = 50
SIM_HZ = 200


class ActorMLP(nn.Module):
    """Match rsl_rl's ActorCritic actor: Linear-ELU stack ending in mean head."""

    def __init__(self, obs_dim: int, action_dim: int, hidden=(256, 256, 128)):
        super().__init__()
        dims = [obs_dim, *hidden, action_dim]
        layers: list[nn.Module] = []
        for i in range(len(dims) - 1):
            layers.append(nn.Linear(dims[i], dims[i + 1]))
            if i < len(dims) - 2:
                layers.append(nn.ELU())
        self.mlp = nn.Sequential(*layers)

    def forward(self, obs: torch.Tensor) -> torch.Tensor:
        return self.mlp(obs)


def load_actor(checkpoint_path: Path, obs_dim: int, action_dim: int) -> ActorMLP:
    ckpt = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
    if "actor_state_dict" not in ckpt:
        raise KeyError(
            f"checkpoint missing 'actor_state_dict' key. available: {list(ckpt.keys())}"
        )
    actor = ActorMLP(obs_dim, action_dim)
    # Drop the Gaussian std parameter — we deploy the deterministic mean.
    mlp_state = {k: v for k, v in ckpt["actor_state_dict"].items() if k.startswith("mlp.")}
    actor.load_state_dict(mlp_state, strict=True)
    actor.eval()
    for p in actor.parameters():
        p.requires_grad_(False)
    return actor


class MujocoDeployer:
    def __init__(self, mjcf_path: Path):
        self.model = mujoco.MjModel.from_xml_path(str(mjcf_path))
        # Ensure sim timestep matches the trained env's 200 Hz.
        self.model.opt.timestep = 1.0 / SIM_HZ
        self.data = mujoco.MjData(self.model)

        self.base_id = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_BODY, "base")
        if self.base_id < 0:
            raise RuntimeError("body 'base' not found in MJCF")

        # qpos/qvel addresses of the 12 actuated joints.
        self.qpos_idx = []
        self.qvel_idx = []
        for name in ACTUATED_JOINTS:
            jid = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_JOINT, name)
            if jid < 0:
                raise RuntimeError(f"actuated joint '{name}' not in MJCF")
            self.qpos_idx.append(self.model.jnt_qposadr[jid])
            self.qvel_idx.append(self.model.jnt_dofadr[jid])
        self.qpos_idx = np.array(self.qpos_idx, dtype=int)
        self.qvel_idx = np.array(self.qvel_idx, dtype=int)

        # Map actuators by name to make sure ctrl order matches ACTUATED_JOINTS.
        self.ctrl_idx = []
        for jname in ACTUATED_JOINTS:
            aid = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_ACTUATOR, f"act_{jname}")
            if aid < 0:
                raise RuntimeError(f"actuator 'act_{jname}' not in MJCF")
            self.ctrl_idx.append(aid)
        self.ctrl_idx = np.array(self.ctrl_idx, dtype=int)

        self.prev_actions = np.zeros(12, dtype=np.float32)

    def reset(self) -> None:
        mujoco.mj_resetData(self.model, self.data)
        # Free joint qpos: [px py pz, qw qx qy qz]
        self.data.qpos[0:3] = [0.0, 0.0, INIT_HEIGHT]
        self.data.qpos[3:7] = INIT_QUAT_WXYZ
        # Set actuated joints to default pose; other (passive) joints stay at 0.
        self.data.qpos[self.qpos_idx] = DEFAULT_JOINT_POS
        self.data.qvel[:] = 0.0
        self.prev_actions[:] = 0.0
        mujoco.mj_forward(self.model, self.data)

    def observe(self) -> np.ndarray:
        # Velocities of the base body in body-local frame (linear, angular).
        vel6 = np.zeros(6)
        mujoco.mj_objectVelocity(self.model, self.data, mujoco.mjtObj.mjOBJ_BODY,
                                  self.base_id, vel6, 1)  # 1 = local frame
        ang_body = vel6[:3]
        lin_body = vel6[3:6]

        # Projected gravity in body frame: R^T * (0, 0, -1) where R is base-to-world.
        base_rot = self.data.xmat[self.base_id].reshape(3, 3)
        gravity_body = base_rot.T @ np.array([0.0, 0.0, -1.0])

        joint_pos = self.data.qpos[self.qpos_idx]
        joint_vel = self.data.qvel[self.qvel_idx]
        joint_pos_rel = joint_pos - DEFAULT_JOINT_POS

        obs = np.concatenate([
            lin_body, ang_body, gravity_body,
            joint_pos_rel, joint_vel, self.prev_actions,
        ]).astype(np.float32)
        obs = np.nan_to_num(obs, nan=0.0, posinf=0.0, neginf=0.0)
        return obs

    def apply_action(self, action: np.ndarray) -> None:
        # Mirror Isaac Lab: clip then `processed = scale * action + default_pos`.
        clipped = np.clip(action, -ACTION_CLIP, ACTION_CLIP)
        target = ACTION_SCALE * clipped + DEFAULT_JOINT_POS
        # ctrl_idx[i] is the MuJoCo actuator index, target[i] the target qpos
        # for the joint that actuator drives — they're in the same order.
        for i, aid in enumerate(self.ctrl_idx):
            self.data.ctrl[aid] = target[i]
        self.prev_actions[:] = clipped


def run_loop(args) -> int:
    mjcf = Path(args.mjcf)
    if not mjcf.exists():
        print(f"[error] MJCF not found at {mjcf}. Run tools/usd_to_mjcf.py first.", file=sys.stderr)
        return 1

    deployer = MujocoDeployer(mjcf)
    deployer.reset()
    actor = load_actor(Path(args.checkpoint), obs_dim=45, action_dim=12)

    decimation = SIM_HZ // CONTROL_HZ
    control_dt = 1.0 / CONTROL_HZ
    max_control_steps = int(args.duration * CONTROL_HZ) if args.duration > 0 else None

    def step_control(step_i: int) -> bool:
        obs = deployer.observe()
        with torch.no_grad():
            action = actor(torch.from_numpy(obs).unsqueeze(0)).squeeze(0).numpy()
        deployer.apply_action(action)
        for _ in range(decimation):
            mujoco.mj_step(deployer.model, deployer.data)
        if not np.all(np.isfinite(deployer.data.qpos)):
            print(f"[warn] non-finite qpos at control step {step_i}; resetting.")
            deployer.reset()
            return False
        return True

    if args.headless:
        print(f"[info] headless run for {args.duration:.1f}s @ {CONTROL_HZ} Hz control")
        t0 = time.time()
        for k in range(max_control_steps or 0):
            step_control(k)
        elapsed = time.time() - t0
        base = deployer.data.qpos[:3]
        print(f"[info] {max_control_steps} steps in {elapsed:.2f}s "
              f"(realtime ratio {(max_control_steps * control_dt) / elapsed:.2f})")
        print(f"[info] base pos = ({base[0]:+.3f}, {base[1]:+.3f}, {base[2]:+.3f})")
        return 0

    with mujoco.viewer.launch_passive(deployer.model, deployer.data) as viewer:
        print("[info] viewer launched. press Esc to quit.")
        k = 0
        next_tick = time.time()
        while viewer.is_running():
            if max_control_steps is not None and k >= max_control_steps:
                break
            step_control(k)
            viewer.sync()
            k += 1
            next_tick += control_dt
            sleep = next_tick - time.time()
            if sleep > 0:
                time.sleep(sleep)
            else:
                next_tick = time.time()
    return 0


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--mjcf", default=str(DEFAULT_MJCF))
    ap.add_argument("--checkpoint", required=True,
                    help=".pt file from rsl_rl (must contain actor_state_dict).")
    ap.add_argument("--headless", action="store_true",
                    help="step without launching the viewer (useful over SSH).")
    ap.add_argument("--duration", type=float, default=0.0,
                    help="run for this many seconds; 0 = unlimited (viewer mode) "
                         "or required positive for headless mode.")
    return ap.parse_args()


if __name__ == "__main__":
    args = parse_args()
    if args.headless and args.duration <= 0:
        print("[error] --headless requires --duration > 0", file=sys.stderr)
        sys.exit(2)
    sys.exit(run_loop(args))
